add aws_get_instance_id.sh script

diff --git a/rcfiles/aliases b/rcfiles/aliases
--- a/rcfiles/aliases
+++ b/rcfiles/aliases
@@ -272,6 +272,7 @@ aws-ssh(){
          profile="$2"
       fi
       instance_id=$(aws --profile ${profile} ec2 describe-instances --filter "Name=tag:Name,Values=${instance_name}" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[]" --output text)
+      echo ${instance_id}
       if [ $? -eq 0 ] && [ "${instance_id}" != "" ]; then
           aws --profile ${profile} ssm start-session --target ${instance_id}
       else
@@ -286,10 +287,21 @@ aws-ssm-ports(){
   instance_name=${1}
   remote_port=${2}
   local_port=${3}
-  if [ $# -eq 3 ]; then
+  if [ $# -lt 3 ]; then
+      profile="default"
+      if [ "$4" != "" ]; then
+         cat ~/.aws/credentials | grep "\[$4\]"
+         if [ $? -ne 0 ]; then
+             echo "profile $4 not in ~/.aws/credentials.... abort.." 
+             return -1
+         fi  
+         profile="$4"
+      fi
+      
       instance_id=$(aws ec2 describe-instances --filter "Name=tag:Name,Values=${instance_name}" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[]" --output text)
+      echo ${instance_id}
       if [ $? -eq 0 ] && [ "${instance_id}" != "" ]; then
-          aws ssm start-session --target ${instance_id} --document-name AWS-StartPortForwardingSession --parameters "{\"portNumber\":[\"${remote_port}\"], \"localPortNumber\":[\"${local_port}\"]}"
+          aws --profile ${profile} ssm start-session --target ${instance_id} --document-name AWS-StartPortForwardingSession --parameters "{\"portNumber\":[\"${remote_port}\"], \"localPortNumber\":[\"${local_port}\"]}"
       else
          echo "[ERROR] $1 does not exist or is not running"
       fi
